repos:
-   repo: https://github.com/ambv/black
    rev: 21.11b1
    hooks:
    - id: black
      stages: [push]
      language_version: python3.7
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      stages: [push]