analysis:
    overwrite: yes
    picks: eeg
    mode: con
    conditions:
        - triplet
power:
    is_evoked: no
    morlet:
        fmin: 4
        fmax: 45
        step: 30
        decim: 1
    postfix: tfr.h5
erp:
    method: median
    postfix: ave.fif.gz
con:
    tmin: 0.0
    tmax: 0.75
    use_laplace: no
    method: wpli
    postfix: con.nc
    bands:
        theta:
            - 4.0
            - 8.0
        alpha:
            - 8.0
            - 13.0
        beta:
            - 13.0
            - 30.0
        gamma:
            - 30.0
            - 45.0
